name: Publish BDD Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Calculator/Calculator.Domain.Tests

      - name: Build solution
        run: dotnet build Calculator/Calculator.sln --configuration Release --no-restore

      - name: Run tests with BDD report output
        run: |
          dotnet test Calculator/Calculator.Domain.Tests \
            --logger "trx;LogFileName=TestResults.trx" \
            --results-directory ./TestResults

      - name: Install SpecFlow.Plus.LivingDoc CLI (if using LivingDoc for BDD report)
        run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Generate BDD Report (LivingDoc)
        run: livingdoc test-assembly Calculator/Calculator.Domain.Tests/bin/Release/net7.0/Calculator.Domain.Tests.dll --output ./docs/bdd-report.html

      - name: Deploy BDD Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
